<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bfr"
    nsURI="http://bfr.bund.de" nsPrefix="bfr">
  <eClassifiers xsi:type="ecore:EClass" name="Literatur">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="erstautor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jahr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literaturAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freigabeModus" lowerBound="1"
        eType="#//FreigabeTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webseite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literaturTyp" lowerBound="1"
        eType="#//LiteraturTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FreigabeTyp">
    <eLiterals name="KEINE" literal="Keine"/>
    <eLiterals name="KRISE" value="1" literal="Krise"/>
    <eLiterals name="IMMER" value="2" literal="Immer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LiteraturTyp">
    <eLiterals name="UNBEKANNT" literal="unbekannt"/>
    <eLiterals name="PAPER" value="1" literal="Paper"/>
    <eLiterals name="BOOK" value="6" literal="Buch"/>
    <eLiterals name="LA" value="3" literal="LA"/>
    <eLiterals name="MANUAL" value="4" literal="Handbuch"/>
    <eLiterals name="TEST_BOOK" value="5" literal="Laborbuch"/>
    <eLiterals name="SOP" value="2" literal="SOP"/>
    <eLiterals name="WEBSITE" value="7" literal="Webseite"/>
    <eLiterals name="REPORT" value="8" literal="Bericht"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LevelTyp">
    <eLiterals name="NONE" literal="keiner"/>
    <eLiterals name="PRIMARY" value="1" literal="Primary"/>
    <eLiterals name="SECONDARY" value="2" literal="Secondary"/>
    <eLiterals name="OTHER" value="3" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KlasseTyp">
    <eLiterals name="UNKNOWN" literal="Unbekannt"/>
    <eLiterals name="GROWTH" value="1" literal="Growth"/>
    <eLiterals name="INACTIVATION" value="2" literal="Inactivation"/>
    <eLiterals name="SURVIVAL" value="3" literal="Survival"/>
    <eLiterals name="GROWTH_INACTIVATION" value="4" literal="Growth/Inactivation"/>
    <eLiterals name="INACTIVATION_SURVIVAL" value="5" literal="Inactivation/Survival"/>
    <eLiterals name="GROWTH_SURVIVAL" value="6" literal="Growth/Survival"/>
    <eLiterals name="GROWTH_INACTIVATION_SURVIVAL" value="7" literal="Growth/Inactivation/Survival"/>
    <eLiterals name="T" value="8"/>
    <eLiterals name="PH" value="9" literal="pH"/>
    <eLiterals name="AW" value="10" literal="aw"/>
    <eLiterals name="T_PH" value="11" literal="T/pH"/>
    <eLiterals name="T_AW" value="12" literal="T/aw"/>
    <eLiterals name="PH_AW" value="13" literal="pH/aw"/>
    <eLiterals name="T_PH_AW" value="14" literal="T/pH/aw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatistikModell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//LevelTyp"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="klasse" eType="#//KlasseTyp"
        defaultValueLiteral="UNKNOWN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eingabedatum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benutzer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="software" eType="#//SoftwareType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//StatistikModellParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literatur" upperBound="-1"
        eType="#//Literatur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatistikModellParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//ParameterRoleType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatistikModellKatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelle" upperBound="-1"
        eType="#//StatistikModell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteraturListe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literatur" upperBound="-1"
        eType="#//Literatur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeschaetztStatistikModell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistikModel" lowerBound="1"
        eType="#//StatistikModell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manuellEingetragen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rSquared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//GeschModellParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedingung" eType="#//VersuchsBedingung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literatur" upperBound="-1"
        eType="#//Literatur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterCovCor" upperBound="-1"
        eType="#//ParameterCovCor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//StatistikModellParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeschModellParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wert" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versuchsBedingung" lowerBound="1"
        eType="#//VersuchsBedingung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="t" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geschaetztesModell" lowerBound="1"
        eType="#//GeschaetztStatistikModell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelParameter" lowerBound="1"
        eType="#//StatistikModellParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kiOben" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kiUnten" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersuchsBedingung">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCB" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeschModelList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//GeschaetztStatistikModell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersuchsBedingungList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedingungen" upperBound="-1"
        eType="#//VersuchsBedingung" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SoftwareType">
    <eLiterals name="NONE" literal="keine"/>
    <eLiterals name="PMP" value="1" literal="Pathogen Modeling Program (PMP)"/>
    <eLiterals name="COMBASE_PREDICTOR" value="2" literal="Combase Predictor"/>
    <eLiterals name="R" value="3"/>
    <eLiterals name="OTHER" value="4" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterRoleType">
    <eLiterals name="NONE" literal="keine"/>
    <eLiterals name="INDEPENDENT" value="1" literal="Independent variable"/>
    <eLiterals name="DEPENDENT" value="3" literal="Dependent variable"/>
    <eLiterals name="PARAMETER" value="2" literal="Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Messwerte">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geprueft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zeitEinheit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aw" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="co2" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="druck" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="temperatur" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pH" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="konzentration" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zeit" eType="#//DoubleKennzahlen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sonstiges" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versuchsbedingungen" eType="#//VersuchsBedingung"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="konzEinheit" eType="#//Einheiten"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleKennzahlen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionXG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionZeit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionZeitG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lcl95" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lcl95G" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="median" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medianG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standardabweichung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standardabweichungG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times10PowerOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ucl95" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ucl95G" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefinedND" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verteilung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verteilungG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wert" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wertG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wertTyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wiederholungen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wiederholungenG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCovCor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter1" lowerBound="1"
        eType="#//GeschModellParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter2" eType="#//GeschModellParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Einheiten">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Einheit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
