/*******************************************************************************
 * Copyright (c) 2015 Federal Institute for Risk Assessment (BfR), Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 *     Department Biological Safety - BfR
 *******************************************************************************/
package de.bund.bfr.knime.pmm.openfsmr;

import de.bund.bfr.knime.pmm.common.generictablemodel.KnimeSchema;

/**
 * Schema for the OpenFSMR template.
 *
 * @author Miguel Alba
 */
public class OpenFSMRSchema extends KnimeSchema {
	
	public static final String ATT_MODEL_NAME = "Model_Name";
	public static final String ATT_MODEL_ID = "Model_ID";
	public static final String ATT_MODEL_LINK = "Model_Link";
	public static final String ATT_ORGANISM_NAME = "PMF_Organism";
	public static final String ATT_ORGANISM_DETAIL = "PMF_Organism_Detail";
	public static final String ATT_ENVIRONMENT_NAME = "PMF_Environment";
	public static final String ATT_ENVIRONMENT_DETAIL = "PMF_Environment_Detail";
	public static final String ATT_MODEL_CREATOR = "Model_Creator";
	public static final String ATT_MODEL_REFERENCE_DESCRIPTION = "Model_Reference_Description";
	public static final String ATT_MODEL_REFERENCE_DESCRIPTION_LINK = "Model_Reference_Description_Link";
	public static final String ATT_MODEL_CREATED_DATE = "Model_Created";
	public static final String ATT_MODEL_MODIFIED = "Model_Modified";
	public static final String ATT_MODEL_RIGHTS = "Model_Rights";
	public static final String ATT_MODEL_NOTES = "Model_Notes";
	public static final String ATT_MODEL_CURATION_STATUS = "Model_Curation_Status";
	public static final String ATT_MODEL_TYPE = "Model_Type";
	public static final String ATT_MODEL_SUBJECT = "Model_Subject";
	public static final String ATT_MODEL_FOOD_PROCESS = "Model_Food_Process";
	public static final String ATT_MODEL_DEPENDENT_VARIABLE = "Model_Dependent_Variable";
	public static final String ATT_MODEL_DEPENDENT_VARIABLE_UNIT = "Model_Dependent_Variable_Unit";
	public static final String ATT_MODEL_DEPENDENT_VARIABLE_MIN = "Model_Dependent_Variable_Min";
	public static final String ATT_MODEL_DEPENDENT_VARIABLE_MAX = "Model_Dependent_Variable_Max";
	public static final String ATT_INDEPENDENT_VARIABLE = "Model_Independent_Variable";
	public static final String ATT_SOFTWARE = "Software";
	public static final String ATT_SOFTWARE_LINK = "Software_Link";
	public static final String ATT_SOFTWARE_NOTES = "Software_Notes";
	public static final String ATT_ACCESIBILITY = "Software_Accesibility";
	public static final String ATT_SOFTWARE_STOCHASTIC_MODELING = "Software_Stochastic_Modeling?";
	public static final String ATT_SOFTWARE_PREDICTION_CONDITIONS = "Software_Prediction_Conditions?";
	public static final String ATT_ATMOSPHERE = "Atmosphere";
	public static final String ATT_INIT_LEVEL_UNIT = "Init_Level_Unit";
	public static final String ATT_INIT_LEVEL_MIN = "Init_Level_Min";
	public static final String ATT_INIT_LEVEL_MAX = "Init_Level_Max";
	public static final String ATT_TIME_UNIT = "Time_Unit";
	public static final String ATT_TIME_MIN = "Time_Min";
	public static final String ATT_TIME_MAX = "Time_Max";
	public static final String ATT_TEMP_UNIT = "Temp_Unit";
	public static final String ATT_TEMP_MIN = "Temp_Min";
	public static final String ATT_TEMP_MAX = "Temp_Max";
	public static final String ATT_PH_UNIT = "Ph_Unit";
	public static final String ATT_PH_MIN = "Ph_Min";
	public static final String ATT_PH_MAX = "Ph_Max";
	public static final String ATT_AW_UNIT = "Aw_Unit";
	public static final String ATT_AW_MIN = "Aw_Min";
	public static final String ATT_AW_MAX = "Aw_Max";
	public static final String ATT_NaCl_UNIT = "NaCl_Unit";
	public static final String ATT_NaCl_MIN = "NaCl_Min";
	public static final String ATT_NaCl_MAX = "NaCl_Max";
	public static final String ATT_ALTA_UNIT = "Alta_Unit";
	public static final String ATT_ALTA_MIN = "Alta_Min";
	public static final String ATT_ALTA_MAX = "Alta_Max";
	public static final String ATT_CO2_UNIT = "CO2_Unit";
	public static final String ATT_CO2_MIN = "CO2_Min";
	public static final String ATT_CO2_MAX = "CO2_Max";
	public static final String ATT_ClO2_UNIT = "ClO2_Unit";
	public static final String ATT_ClO2_MIN = "ClO2_Min";
	public static final String ATT_ClO2_MAX = "ClO2_Max";
	public static final String ATT_EDTA_UNIT = "Edta_Unit";
	public static final String ATT_EDTA_MIN = "Edta_Min";
	public static final String ATT_EDTA_MAX = "Edta_Max";
	public static final String ATT_HCl_UNIT = "HCl_Unit";
	public static final String ATT_HCl_MIN = "HCl_Min";
	public static final String ATT_HCl_MAX = "HCl_Max";
	public static final String ATT_N2_UNIT = "N2_Unit";
	public static final String ATT_N2_MIN = "N2_Min";
	public static final String ATT_N2_MAX = "N2_Max";
	public static final String ATT_O2_UNIT = "O2_Unit";
	public static final String ATT_O2_MIN = "O2_Min";
	public static final String ATT_O2_MAX = "O2_Max";
	public static final String ATT_ACETIC_ACID_UNIT = "Acetic_Acid_Unit";
	public static final String ATT_ACETIC_ACID_MIN = "Acetic_Acid_Min";
	public static final String ATT_ACETIC_ACID_MAX = "Acetic_Acid_Max";
	public static final String ATT_ADDITIVES = "Additives";
	public static final String ATT_ANAEROBIC = "Anaerobic";
	public static final String ATT_ANTIMICROBIAL_DIPPING_TIME_UNIT = "Antimicrobial_Dipping_Time_Unit";
	public static final String ATT_ANTIMICROBIAL_DIPPING_TIME_MIN = "Antimicrobial_Dipping_Time_Min";
	public static final String ATT_ANTIMICROBIAL_DIPPING_TIME_MAX = "Antimicrobial_Dipping_Time_Max";
	public static final String ATT_APPLE_POLYPHENOL_UNIT = "Apple_Polyphenol_Unit";
	public static final String ATT_APPLE_POLYPHENOL_MIN = "Apple_Polyphenol_Min";
	public static final String ATT_APPLE_POLYPHENOL_MAX = "Apple_Polyphenol_Max";
	public static final String ATT_ASCORBICC_ACID_UNIT = "Ascorbicc_Acid_Unit";
	public static final String ATT_ASCORBICC_ACID_MIN = "Ascorbicc_Acid_Min";
	public static final String ATT_ASCORBICC_ACID_MAX = "Ascorbicc_Acid_Max";
	public static final String ATT_ATR_INDUCED = "Atr_Induced";
	public static final String ATT_ATTACHMENT_TIME_UNIT = "Attachment_Time_Unit";
	public static final String ATT_ATTACHMENT_TIME_MIN = "Attachment_Time_Min";
	public static final String ATT_ATTACHMENT_TIME_MAX = "Attachment_Time_Max";
	public static final String ATT_BEAN_OIL_UNIT = "Bean_Oil_Unit";
	public static final String ATT_BEAN_OIL_MIN = "Bean_Oil_Min";
	public static final String ATT_BEAN_OIL_MAX = "Bean_Oil_Max";
	public static final String ATT_BENZOIC_ACID_UNIT = "Benzoic_Acid_Unit";
	public static final String ATT_BENZOIC_ACID_MIN = "Benzoic_Acid_Min";
	public static final String ATT_BENZOIC_ACID_MAX = "Benzoic_Acid_Max";
	public static final String ATT_BETAINE_UNIT = "Betaine_Unit";
	public static final String ATT_BETAINE_MIN = "Betaine_Min";
	public static final String ATT_BETAINE_MAX = "Betaine_Max";
	public static final String ATT_CARVACROL_UNIT = "Carvacrol_Unit";
	public static final String ATT_CARVACROL_MIN = "Carvacrol_Min";
	public static final String ATT_CARVACROL_MAX = "Carvacrol_Max";
	public static final String ATT_CHITOSAN_UNIT = "Chitosan_Unit";
	public static final String ATT_CHITOSAN_MIN = "Chitosan_Min";
	public static final String ATT_CHITOSAN_MAX = "Chitosan_Max";
	public static final String ATT_CINNAMALDEHYDE_UNIT = "Cinnamaldehyde_Unit";
	public static final String ATT_CINNAMALDEHYDE_MIN = "Cinnamaldehyde_Min";
	public static final String ATT_CINNAMALDEHYDE_MAX = "Cinnamaldehyde_Max";
	public static final String ATT_CITRIC_ACID_UNIT = "Citric_Acid_Unit";
	public static final String ATT_CITRIC_ACID_MIN = "Citric_Acid_Min";
	public static final String ATT_CITRIC_ACID_MAX = "Citric_Acid_Max";
	public static final String ATT_CO_CULTURE = "Co_Culture";
	public static final String ATT_CURED = "Cured";
	public static final String ATT_DESIRED_REDUCTION_UNIT = "Desired_Reduction_Unit";
	public static final String ATT_DESIRED_REDUCTION_MIN = "Desired_Reduction_Min";
	public static final String ATT_DESIRED_REDUCTION_MAX = "Desired_Reduction_Max";
	public static final String ATT_DIACETIC_ACID_UNIT = "Diacetic_Acid_Unit";
	public static final String ATT_DIACETIC_ACID_MIN = "Diacetic_Acid_Min";
	public static final String ATT_DIACETIC_ACID_MAX = "Diacetic_Acid_Max";
	public static final String ATT_DISACCHARIDE_UNIT = "Disaccharide_Unit";
	public static final String ATT_DISACCHARIDE_MIN = "Disaccharide_Min";
	public static final String ATT_DISACCHARIDE_MAX = "Disaccharide_Max";
	public static final String ATT_DRIED = "Dried";
	public static final String ATT_ETHANOL_UNIT = "Ethanol_Unit";
	public static final String ATT_ETHANOL_MIN = "Ethanol_Min";
	public static final String ATT_ETHANOL_MAX = "Ethanol_Max";
	public static final String ATT_EXP_INOCULATED = "Exp_Inoculated";
	public static final String ATT_FAT_UNIT = "Fat_Unit";
	public static final String ATT_FAT_MIN = "Fat_Min";
	public static final String ATT_FAT_MAX = "Fat_Max";
	public static final String ATT_FROZEN = "Frozen";
	public static final String ATT_FRUCTOSE_UNIT = "Fructose_Unit";
	public static final String ATT_FRUCTOSE_MIN = "Fructose_Min";
	public static final String ATT_FRUCTOSE_MAX = "Fructose_Max";
	public static final String ATT_GEL_MICROSTRUCTURE_UNIT = "Gel_microstructure_Unit";
	public static final String ATT_GEL_MICROSTRUCTURE_MIN = "Gel_microstructure_Min";
	public static final String ATT_GEL_MICROSTRUCTURE_MAX = "Gel_microstructure_Max";
	public static final String ATT_GLUCOSE_UNIT = "Glucose_Unit";
	public static final String ATT_GLUCOSE_MIN = "Glucose_Min";
	public static final String ATT_GLUCOSE_MAX = "Glucose_Max";
	public static final String ATT_GLYCEROL_UNIT = "Glycerol_Unit";
	public static final String ATT_GLYCEROL_MIN = "Glycerol_Min";
	public static final String ATT_GLYCEROL_MAX = "Glycerol_Max";
	public static final String ATT_GREEN_TEA_GROUND_POWDER_UNIT = "Green_Tea_Ground_Powder_Unit";
	public static final String ATT_GREEN_TEA_GROUND_POWDER_MIN = "Green_Tea_Ground_Powder_Min";
	public static final String ATT_GREEN_TEA_GROUND_POWDER_MAX = "Green_Tea_Ground_Powder_Max";
	public static final String ATT_GREEN_TEA_LEAF_UNIT = "Green_Tea_Leaf_Unit";
	public static final String ATT_GREEN_TEA_LEAF_MIN = "Green_Tea_Leaf_Min";
	public static final String ATT_GREEN_TEA_LEAF_MAX = "Green_Tea_Leaf_Max";
	public static final String ATT_GREEN_TEA_POLYPHENOL_UNIT = "Green_Tea_Polyphenol_Unit";
	public static final String ATT_GREEN_TEA_POLYPHENOL_MIN = "Green_Tea_Polyphenol_Min";
	public static final String ATT_GREEN_TEA_POLYPHENOL_MAX = "Green_Tea_Polyphenol_Max";
	public static final String ATT_GREEN_TEA_WATER_EXTRACT_UNIT = "Green_Tea_Water_Extract_Unit";
	public static final String ATT_GREEN_TEA_WATER_EXTRACT_MIN = "Green_Tea_Water_Extract_Min";
	public static final String ATT_GREEN_TEA_WATER_EXTRACT_MAX = "Green_Tea_Water_Extract_Max";
	public static final String ATT_HEATED = "Heated";
	public static final String ATT_HEXOSES_UNIT = "Hexoses_Unit";
	public static final String ATT_HEXOSES_MIN = "Hexoses_Min";
	public static final String ATT_HEXOSES_MAX = "Hexoses_Max";
	public static final String ATT_INDIGENOUS = "Indigenous";
	public static final String ATT_INIT_LEVEL_HISTAMINE_UNIT = "Init_Level_Histamine_Unit";
	public static final String ATT_INIT_LEVEL_HISTAMINE_MIN = "Init_Level_Histamine_Min";
	public static final String ATT_INIT_LEVEL_HISTAMINE_MAX = "Init_Level_Histamine_Max";
	public static final String ATT_INIT_LEVEL_HISTIDINE_UNIT = "Init_Level_Histidine_Unit";
	public static final String ATT_INIT_LEVEL_HISTIDINE_MIN = "Init_Level_Histidine_Min";
	public static final String ATT_INIT_LEVEL_HISTIDINE_MAX = "Init_Level_Histidine_Max";
	public static final String ATT_INJURED_UNIT = "Injured_Unit";
	public static final String ATT_INJURED_MIN = "Injured_Min";
	public static final String ATT_INJURED_MAX = "Injured_Max";
	public static final String ATT_IRRADIATED = "Irradiated";
	public static final String ATT_IRRADIATION_UNIT = "Irradation_Unit";
	public static final String ATT_IRRADIATION_MIN = "Irradation_Min";
	public static final String ATT_IRRADIATION_MAX = "Irradation_Max";
	public static final String ATT_LACTIC_ACID_UNIT = "Lactic_Acid_Unit";
	public static final String ATT_LACTIC_ACID_MIN = "Lactic_Acid_Min";
	public static final String ATT_LACTIC_ACID_MAX = "Lactic_Acid_Max";
	public static final String ATT_LACTIC_BACTERIA_FERMENTED = "Lactic_Bacteria_Fermented";
	public static final String ATT_LAURICIDIN_UNIT = "Lauricidin_Unit";
	public static final String ATT_LAURICIDIN_MIN = "Lauricidin_Min";
	public static final String ATT_LAURICIDIN_MAX = "Lauricidin_Max";
	public static final String ATT_MALIC_ACID_UNIT = "Malic_Acid_Unit";
	public static final String ATT_MALIC_ACID_MIN = "Malic_Acid_Min";
	public static final String ATT_MALIC_ACID_MAX = "Malic_Acid_Max";

	public OpenFSMRSchema() {
		addStringAttribute(ATT_MODEL_NAME);
		addStringAttribute(ATT_MODEL_ID);
		addStringAttribute(ATT_MODEL_LINK);
		addStringAttribute(ATT_ORGANISM_NAME);
		addStringAttribute(ATT_ORGANISM_DETAIL);
		addStringAttribute(ATT_ENVIRONMENT_NAME);
		addStringAttribute(ATT_ENVIRONMENT_DETAIL);
		addStringAttribute(ATT_MODEL_CREATOR);
		addStringAttribute(ATT_MODEL_REFERENCE_DESCRIPTION);
		addStringAttribute(ATT_MODEL_REFERENCE_DESCRIPTION_LINK);
		addStringAttribute(ATT_MODEL_CREATED_DATE);
		addStringAttribute(ATT_MODEL_MODIFIED);
		addStringAttribute(ATT_MODEL_RIGHTS);
		addStringAttribute(ATT_MODEL_NOTES);
		addStringAttribute(ATT_MODEL_CURATION_STATUS);
		addStringAttribute(ATT_MODEL_TYPE);
		addStringAttribute(ATT_MODEL_SUBJECT);
		addStringAttribute(ATT_MODEL_FOOD_PROCESS);
		addStringAttribute(ATT_MODEL_DEPENDENT_VARIABLE);
		addStringAttribute(ATT_MODEL_DEPENDENT_VARIABLE_UNIT);
		addDoubleAttribute(ATT_MODEL_DEPENDENT_VARIABLE_MIN);
		addDoubleAttribute(ATT_MODEL_DEPENDENT_VARIABLE_MAX);
		addStringAttribute(ATT_INDEPENDENT_VARIABLE);
		addStringAttribute(ATT_SOFTWARE);
		addStringAttribute(ATT_SOFTWARE_LINK);
		addStringAttribute(ATT_SOFTWARE_NOTES);
		addStringAttribute(ATT_ACCESIBILITY);
		addIntAttribute(ATT_SOFTWARE_STOCHASTIC_MODELING);
		addIntAttribute(ATT_SOFTWARE_PREDICTION_CONDITIONS);
		addStringAttribute(ATT_ATMOSPHERE);
		addStringAttribute(ATT_INIT_LEVEL_UNIT);
		addDoubleAttribute(ATT_INIT_LEVEL_MIN);
		addDoubleAttribute(ATT_INIT_LEVEL_MAX);
		addStringAttribute(ATT_TIME_UNIT);
		addDoubleAttribute(ATT_TIME_MIN);
		addDoubleAttribute(ATT_TIME_MAX);
		addStringAttribute(ATT_TEMP_UNIT);
		addDoubleAttribute(ATT_TEMP_MIN);
		addDoubleAttribute(ATT_TEMP_MAX);
		addStringAttribute(ATT_PH_UNIT);
		addDoubleAttribute(ATT_PH_MIN);
		addDoubleAttribute(ATT_PH_MAX);
		addStringAttribute(ATT_AW_UNIT);
		addDoubleAttribute(ATT_AW_MIN);
		addDoubleAttribute(ATT_AW_MAX);
		addStringAttribute(ATT_NaCl_UNIT);
		addDoubleAttribute(ATT_NaCl_MIN);
		addDoubleAttribute(ATT_NaCl_MAX);
		addStringAttribute(ATT_ALTA_UNIT);
		addDoubleAttribute(ATT_ALTA_MIN);
		addDoubleAttribute(ATT_ALTA_MAX);
		addStringAttribute(ATT_CO2_UNIT);
		addDoubleAttribute(ATT_CO2_MIN);
		addDoubleAttribute(ATT_CO2_MAX);
		addStringAttribute(ATT_ClO2_UNIT);
		addDoubleAttribute(ATT_ClO2_MIN);
		addDoubleAttribute(ATT_ClO2_MAX);
		addStringAttribute(ATT_EDTA_UNIT);
		addDoubleAttribute(ATT_EDTA_MIN);
		addDoubleAttribute(ATT_EDTA_MAX);
		addStringAttribute(ATT_HCl_UNIT);
		addDoubleAttribute(ATT_HCl_MIN);
		addDoubleAttribute(ATT_HCl_MAX);
		addStringAttribute(ATT_N2_UNIT);
		addDoubleAttribute(ATT_N2_MIN);
		addDoubleAttribute(ATT_N2_MAX);
		addStringAttribute(ATT_O2_UNIT);
		addDoubleAttribute(ATT_O2_MIN);
		addDoubleAttribute(ATT_O2_MAX);
		addStringAttribute(ATT_ACETIC_ACID_UNIT);
		addDoubleAttribute(ATT_ACETIC_ACID_MIN);
		addDoubleAttribute(ATT_ACETIC_ACID_MAX);
		addStringAttribute(ATT_ADDITIVES);
		addStringAttribute(ATT_ANAEROBIC);
		addStringAttribute(ATT_ANTIMICROBIAL_DIPPING_TIME_UNIT);
		addDoubleAttribute(ATT_ANTIMICROBIAL_DIPPING_TIME_MIN);
		addDoubleAttribute(ATT_ANTIMICROBIAL_DIPPING_TIME_MAX);
		addStringAttribute(ATT_APPLE_POLYPHENOL_UNIT);
		addDoubleAttribute(ATT_APPLE_POLYPHENOL_MIN);
		addDoubleAttribute(ATT_APPLE_POLYPHENOL_MAX);
		addStringAttribute(ATT_ASCORBICC_ACID_UNIT);
		addDoubleAttribute(ATT_ASCORBICC_ACID_MIN);
		addDoubleAttribute(ATT_ASCORBICC_ACID_MAX);
		addStringAttribute(ATT_ATR_INDUCED);
		addStringAttribute(ATT_ATTACHMENT_TIME_UNIT);
		addDoubleAttribute(ATT_ATTACHMENT_TIME_MIN);
		addDoubleAttribute(ATT_ATTACHMENT_TIME_MAX);
		addStringAttribute(ATT_BEAN_OIL_UNIT);
		addDoubleAttribute(ATT_BEAN_OIL_MIN);
		addDoubleAttribute(ATT_BEAN_OIL_MAX);
		addStringAttribute(ATT_BENZOIC_ACID_UNIT);
		addDoubleAttribute(ATT_BENZOIC_ACID_MIN);
		addDoubleAttribute(ATT_BENZOIC_ACID_MAX);
		addStringAttribute(ATT_BETAINE_UNIT);
		addDoubleAttribute(ATT_BETAINE_MIN);
		addDoubleAttribute(ATT_BETAINE_MAX);
		addStringAttribute(ATT_CARVACROL_UNIT);
		addDoubleAttribute(ATT_CARVACROL_MIN);
		addDoubleAttribute(ATT_CARVACROL_MAX);
		addStringAttribute(ATT_CHITOSAN_UNIT);
		addDoubleAttribute(ATT_CHITOSAN_MIN);
		addDoubleAttribute(ATT_CHITOSAN_MAX);
		addStringAttribute(ATT_CINNAMALDEHYDE_UNIT);
		addDoubleAttribute(ATT_CINNAMALDEHYDE_MIN);
		addDoubleAttribute(ATT_CINNAMALDEHYDE_MAX);
		addStringAttribute(ATT_CITRIC_ACID_UNIT);
		addDoubleAttribute(ATT_CITRIC_ACID_MIN);
		addDoubleAttribute(ATT_CITRIC_ACID_MAX);
		addStringAttribute(ATT_CO_CULTURE);
		addStringAttribute(ATT_CURED);
		addStringAttribute(ATT_DESIRED_REDUCTION_UNIT);
		addDoubleAttribute(ATT_DESIRED_REDUCTION_MIN);
		addDoubleAttribute(ATT_DESIRED_REDUCTION_MAX);
		addStringAttribute(ATT_DESIRED_REDUCTION_UNIT);
		addDoubleAttribute(ATT_DESIRED_REDUCTION_MIN);
		addDoubleAttribute(ATT_DESIRED_REDUCTION_MAX);
		addStringAttribute(ATT_DIACETIC_ACID_UNIT);
		addDoubleAttribute(ATT_DIACETIC_ACID_MIN);
		addDoubleAttribute(ATT_DIACETIC_ACID_MAX);
		addStringAttribute(ATT_DISACCHARIDE_UNIT);
		addDoubleAttribute(ATT_DISACCHARIDE_MIN);
		addDoubleAttribute(ATT_DISACCHARIDE_MAX);
		addStringAttribute(ATT_DRIED);
		addStringAttribute(ATT_ETHANOL_UNIT);
		addDoubleAttribute(ATT_ETHANOL_MIN);
		addDoubleAttribute(ATT_ETHANOL_MAX);
		addStringAttribute(ATT_EXP_INOCULATED);
		addStringAttribute(ATT_FAT_UNIT);
		addDoubleAttribute(ATT_FAT_MIN);
		addDoubleAttribute(ATT_FAT_MAX);
		addStringAttribute(ATT_FROZEN);
		addStringAttribute(ATT_FRUCTOSE_UNIT);
		addDoubleAttribute(ATT_FRUCTOSE_MIN);
		addDoubleAttribute(ATT_FRUCTOSE_MAX);
		addStringAttribute(ATT_GEL_MICROSTRUCTURE_UNIT);
		addDoubleAttribute(ATT_GEL_MICROSTRUCTURE_MIN);
		addDoubleAttribute(ATT_GEL_MICROSTRUCTURE_MAX);
		addStringAttribute(ATT_GLUCOSE_UNIT);
		addDoubleAttribute(ATT_GLUCOSE_MIN);
		addDoubleAttribute(ATT_GLUCOSE_MAX);
		addStringAttribute(ATT_GLYCEROL_UNIT);
		addDoubleAttribute(ATT_GLYCEROL_MIN);
		addDoubleAttribute(ATT_GLYCEROL_MAX);
		addStringAttribute(ATT_GREEN_TEA_GROUND_POWDER_UNIT);
		addDoubleAttribute(ATT_GREEN_TEA_GROUND_POWDER_MIN);
		addDoubleAttribute(ATT_GREEN_TEA_GROUND_POWDER_MAX);
		addStringAttribute(ATT_GREEN_TEA_LEAF_UNIT);
		addDoubleAttribute(ATT_GREEN_TEA_LEAF_MIN);
		addDoubleAttribute(ATT_GREEN_TEA_LEAF_MAX);
		addStringAttribute(ATT_GREEN_TEA_WATER_EXTRACT_UNIT);
		addDoubleAttribute(ATT_GREEN_TEA_WATER_EXTRACT_MIN);
		addDoubleAttribute(ATT_GREEN_TEA_WATER_EXTRACT_MAX);
		addStringAttribute(ATT_HEATED);
		addStringAttribute(ATT_HEXOSES_UNIT);
		addDoubleAttribute(ATT_HEXOSES_MIN);
		addDoubleAttribute(ATT_HEXOSES_MAX);
		addStringAttribute(ATT_INDIGENOUS);
		addStringAttribute(ATT_INIT_LEVEL_HISTAMINE_UNIT);
		addDoubleAttribute(ATT_INIT_LEVEL_HISTAMINE_MIN);
		addDoubleAttribute(ATT_INIT_LEVEL_HISTAMINE_MAX);
		addStringAttribute(ATT_INIT_LEVEL_HISTIDINE_UNIT);
		addDoubleAttribute(ATT_INIT_LEVEL_HISTIDINE_MIN);
		addDoubleAttribute(ATT_INIT_LEVEL_HISTIDINE_MAX);
		addStringAttribute(ATT_INJURED_UNIT);
		addDoubleAttribute(ATT_INJURED_MIN);
		addDoubleAttribute(ATT_INJURED_MAX);
		addStringAttribute(ATT_IRRADIATED);
		addStringAttribute(ATT_IRRADIATION_UNIT);
		addDoubleAttribute(ATT_IRRADIATION_MIN);
		addDoubleAttribute(ATT_IRRADIATION_MAX);
		addStringAttribute(ATT_LACTIC_ACID_UNIT);
		addDoubleAttribute(ATT_LACTIC_ACID_MIN);
		addDoubleAttribute(ATT_LACTIC_ACID_MAX);
		addStringAttribute(ATT_LACTIC_BACTERIA_FERMENTED);
		addStringAttribute(ATT_LAURICIDIN_UNIT);
		addDoubleAttribute(ATT_LAURICIDIN_MIN);
		addDoubleAttribute(ATT_LAURICIDIN_MAX);
		addStringAttribute(ATT_MALIC_ACID_UNIT);
		addDoubleAttribute(ATT_MALIC_ACID_MIN);
		addDoubleAttribute(ATT_MALIC_ACID_MAX);
	}
}
